# You have to configure this ###################################################
title: Hardcode
# You should configure this ####################################################
url: https://hardcode.fm
download_url: "https://hardcode.fm/"
subtitle: Подкаст о практике программирования
description: '*записываемся на утюг'
author: Hardcode Crew
author_url: "https://hardcode.fm"
email: hardcode@razum2um.me
keywords: [podcast, ruby, javascript, clojure]
itunes_categories: [Technology]
episodes_per_feed_page: 100
# Date can be localized via date_de.rb plugin
date_format: "ordinal"
## Rsync Deploy config #########################################################
### Be sure your public key is listed in your server's ~/.ssh/authorized_keys
### file.
ssh_host: hardcode@hardcode.fm
ssh_port: 2223
document_root: /home/hardcode/hardcode
rsync_delete: true
# You can configure this #######################################################
twitter_nick: hardcodefm
language: ru
explicit: 'no'  # 'yes'/'no'/clean
license: CC BY 4.0
license_url: https://creativecommons.org/licenses/by/4.0/
license_image_url: /img/license.png
## Flattr ######################################################################
flattr_uid: # Flattr will not be used unless this is set
flattr_button: compact # compact | default
flattr_mode: auto # auto | manual(default)
flattr_popout:  1 # 1 | 0 (show popout when hovering mouse over button)
flattr_language: en_GB # available languages - https://api.flattr.com/rest/v2/languages.txt
flattr_category: audio # available categories - https://api.flattr.com/rest/v2/categories.txt
## Disqus comments #############################################################
disqus_shortname: # Disqus will not be used unless this is set
disqus_developer: 0 # 1 / 0
## Itunes link ###########################################################
itunes_url: "https://itunes.apple.com/at/podcast/myname/id#myid#"
## Isso comments #########################################################
use_isso: no # set to 'yes' to include isso comments form

plugins:
  - jekyll-octopod
  - jekyll-feed
  - jekyll-admin

theme: jekyll-bootflat

exclude:
  - checkfont.py
  - vendor

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      episode_cover: '/img/logo.svg'
